// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradeSphere.Infrastructure.Persistence;

#nullable disable

namespace TradeSphere.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260627125007_AddCryptoOptionsDesk")]
    partial class AddCryptoOptionsDesk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradeSphere.Domain.Entities.AiScreenerResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalysisData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Signal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("AiScreenerResults");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.Backtest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("InitialCapital")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MaxDrawdown")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("RanAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("StrategyId")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalReturn")
                        .HasColumnType("numeric");

                    b.Property<int?>("TotalTrades")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WinRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.HasIndex("UserId");

                    b.ToTable("Backtests");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ExchangeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Coins");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionBacktestLeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BacktestPositionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("EntryDelta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EntryIv")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EntryPremium")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EntryTheta")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("ExitPremium")
                        .HasColumnType("numeric");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LegType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Pnl")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("StopLossHit")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Strike")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BacktestPositionId");

                    b.ToTable("CryptoOptionBacktestLegs");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionBacktestLegEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BacktestLegId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Pnl")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Premium")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BacktestLegId");

                    b.ToTable("CryptoOptionBacktestLegEvents");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionBacktestPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BacktestRunId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Charges")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("GrossPnl")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsCircuitBreakerHit")
                        .HasColumnType("boolean");

                    b.Property<decimal>("NetPnl")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Underlying")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnderlyingEntryPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnderlyingExitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId");

                    b.ToTable("CryptoOptionBacktestPositions");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionBacktestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Charges")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("GrossPnl")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InitialCapital")
                        .HasColumnType("numeric");

                    b.Property<int>("LosingDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxDrawdown")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProfitFactor")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StrategyConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("TotalPnl")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WinningDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StrategyConfigId");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("CryptoOptionBacktestRuns");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionChainSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CallAsk")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CallBid")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CallDelta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CallGamma")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CallIv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CallOpenInterest")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CallPremium")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CallRho")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CallTheta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CallVega")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CallVolume")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("PutAsk")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PutBid")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PutDelta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PutGamma")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PutIv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PutOpenInterest")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PutPremium")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PutRho")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PutTheta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PutVega")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PutVolume")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("SnapshotTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Strike")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Underlying")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnderlyingPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Exchange", "Symbol", "ExpiryDate", "SnapshotTime");

                    b.HasIndex("Exchange", "Symbol", "ExpiryDate", "Strike", "SnapshotTime");

                    b.ToTable("CryptoOptionChainSnapshots");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionDailyPnl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BacktestRunId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CeLegPnl")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Charges")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("GrossPnl")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsCircuitBreakerHit")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxIntradayLoss")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetPnl")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("PeLegPnl")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId");

                    b.ToTable("CryptoOptionDailyPnls");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionScannerResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BestCallDelta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BestCallIv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BestCallPremium")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BestCallStrike")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BestCallTheta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BestPutDelta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BestPutIv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BestPutPremium")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BestPutStrike")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BestPutTheta")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ProbabilityOfProfit")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ScanTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ScannerMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("StrategyScore")
                        .HasColumnType("numeric");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Exchange", "Symbol", "ScanTime");

                    b.ToTable("CryptoOptionScannerResults");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionStrategyConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtrLength")
                        .HasColumnType("integer");

                    b.Property<decimal>("BrokeragePerOrder")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EmaLength")
                        .HasColumnType("integer");

                    b.Property<string>("EntryTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ExchangeFeePercent")
                        .HasColumnType("numeric");

                    b.Property<string>("ExitTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpiryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LotSize")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxAtrPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxDailyLoss")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxTrendDistancePercent")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SlippagePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StopLossPercentPerLeg")
                        .HasColumnType("numeric");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("StrikeDistancePercent")
                        .HasColumnType("numeric");

                    b.Property<string>("StrikeSelectionMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TargetPremiumPerLeg")
                        .HasColumnType("numeric");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Underlying")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("UseAtrFilter")
                        .HasColumnType("boolean");

                    b.Property<bool>("UseSlippage")
                        .HasColumnType("boolean");

                    b.Property<bool>("UseTrendFilter")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("CryptoOptionStrategyConfigs");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionStrategyLeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExpiryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LegName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("StrategyConfigId")
                        .HasColumnType("integer");

                    b.Property<decimal>("StrikeDistancePercent")
                        .HasColumnType("numeric");

                    b.Property<string>("StrikeSelectionMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TargetPremium")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrategyConfigId");

                    b.ToTable("CryptoOptionStrategyLegs");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.Exchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Exchanges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://api.india.delta.exchange",
                            CreatedAt = new DateTime(2026, 6, 27, 12, 50, 6, 80, DateTimeKind.Utc).AddTicks(6165),
                            IsActive = true,
                            Name = "Delta Exchange India"
                        },
                        new
                        {
                            Id = 2,
                            BaseUrl = "https://api.delta.exchange",
                            CreatedAt = new DateTime(2026, 6, 27, 12, 50, 6, 80, DateTimeKind.Utc).AddTicks(6169),
                            IsActive = true,
                            Name = "Delta Exchange Global"
                        },
                        new
                        {
                            Id = 3,
                            BaseUrl = "https://testnet-api.delta.exchange",
                            CreatedAt = new DateTime(2026, 6, 27, 12, 50, 6, 80, DateTimeKind.Utc).AddTicks(6170),
                            IsActive = true,
                            Name = "Delta Exchange Testnet"
                        });
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.Mt5Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Equity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FreeMargin")
                        .HasColumnType("numeric");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Leverage")
                        .HasColumnType("integer");

                    b.Property<long>("Login")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TradingEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Login", "Server")
                        .IsUnique();

                    b.ToTable("Mt5Accounts");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.Mt5SymbolMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrokerSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Mt5AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("StrategySymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Mt5AccountId");

                    b.HasIndex("UserId", "Mt5AccountId", "StrategySymbol")
                        .IsUnique();

                    b.ToTable("Mt5SymbolMappings");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.PropFirm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("PropFirms");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.PropFirmAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccountSize")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("DailyDrawdownLimit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxDrawdownLimit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxRiskPerTradePercent")
                        .HasColumnType("numeric");

                    b.Property<int>("MinimumTradingDays")
                        .HasColumnType("integer");

                    b.Property<int?>("Mt5AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NewsTradingAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("ProfitTarget")
                        .HasColumnType("numeric");

                    b.Property<int>("PropFirmId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("WeekendHoldingAllowed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Mt5AccountId");

                    b.HasIndex("PropFirmId");

                    b.HasIndex("UserId");

                    b.ToTable("PropFirmAccounts");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.Strategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultConfig")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("LogicType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.StrategyHealthSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsEntryEligible")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuggestedSide")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserStrategyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserStrategyId")
                        .IsUnique();

                    b.ToTable("StrategyHealthSnapshots");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrokerResponse")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ErrorReason")
                        .HasColumnType("text");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExternalOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Pnl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserStrategyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserStrategyId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.UserExchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApiSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserExchanges");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.UserStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("integer");

                    b.Property<string>("ExecutionProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Mt5AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StoppedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("StrategyId")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UserExchangeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("Mt5AccountId");

                    b.HasIndex("StrategyId");

                    b.HasIndex("UserExchangeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserStrategies");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.Backtest", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId");

                    b.HasOne("TradeSphere.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.Coin", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId");

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionBacktestLeg", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.CryptoOptionBacktestPosition", "BacktestPosition")
                        .WithMany("Legs")
                        .HasForeignKey("BacktestPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestPosition");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionBacktestLegEvent", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.CryptoOptionBacktestLeg", "BacktestLeg")
                        .WithMany("Events")
                        .HasForeignKey("BacktestLegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestLeg");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionBacktestPosition", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.CryptoOptionBacktestRun", "BacktestRun")
                        .WithMany("Positions")
                        .HasForeignKey("BacktestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestRun");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionBacktestRun", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.CryptoOptionStrategyConfig", "StrategyConfig")
                        .WithMany()
                        .HasForeignKey("StrategyConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StrategyConfig");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionDailyPnl", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.CryptoOptionBacktestRun", "BacktestRun")
                        .WithMany("DailyPnls")
                        .HasForeignKey("BacktestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestRun");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionStrategyLeg", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.CryptoOptionStrategyConfig", "StrategyConfig")
                        .WithMany("Legs")
                        .HasForeignKey("StrategyConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StrategyConfig");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.Mt5Account", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.Mt5SymbolMapping", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.Mt5Account", "Mt5Account")
                        .WithMany()
                        .HasForeignKey("Mt5AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeSphere.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mt5Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.PropFirm", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.PropFirmAccount", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.Mt5Account", "Mt5Account")
                        .WithMany()
                        .HasForeignKey("Mt5AccountId");

                    b.HasOne("TradeSphere.Domain.Entities.PropFirm", "PropFirm")
                        .WithMany()
                        .HasForeignKey("PropFirmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeSphere.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mt5Account");

                    b.Navigation("PropFirm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.Strategy", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.StrategyHealthSnapshot", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.UserStrategy", "UserStrategy")
                        .WithMany()
                        .HasForeignKey("UserStrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserStrategy");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.Trade", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeSphere.Domain.Entities.User", "User")
                        .WithMany("Trades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeSphere.Domain.Entities.UserStrategy", "UserStrategy")
                        .WithMany()
                        .HasForeignKey("UserStrategyId");

                    b.Navigation("Exchange");

                    b.Navigation("User");

                    b.Navigation("UserStrategy");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.UserExchange", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeSphere.Domain.Entities.User", "User")
                        .WithMany("UserExchanges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.UserStrategy", b =>
                {
                    b.HasOne("TradeSphere.Domain.Entities.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeSphere.Domain.Entities.Mt5Account", "Mt5Account")
                        .WithMany()
                        .HasForeignKey("Mt5AccountId");

                    b.HasOne("TradeSphere.Domain.Entities.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeSphere.Domain.Entities.UserExchange", "UserExchange")
                        .WithMany()
                        .HasForeignKey("UserExchangeId");

                    b.HasOne("TradeSphere.Domain.Entities.User", "User")
                        .WithMany("UserStrategies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");

                    b.Navigation("Mt5Account");

                    b.Navigation("Strategy");

                    b.Navigation("User");

                    b.Navigation("UserExchange");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionBacktestLeg", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionBacktestPosition", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionBacktestRun", b =>
                {
                    b.Navigation("DailyPnls");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.CryptoOptionStrategyConfig", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("TradeSphere.Domain.Entities.User", b =>
                {
                    b.Navigation("Trades");

                    b.Navigation("UserExchanges");

                    b.Navigation("UserStrategies");
                });
#pragma warning restore 612, 618
        }
    }
}
